import { Button, GridBox, VerticalBox, ScrollView, HorizontalBox, ListView, ComboBox, TextEdit } from "std-widgets.slint";
import { BeautifyButton } from "beauty_button.slint";
export component CommandSetWindow inherits Dialog {
    width: 600px;
    height: 400px;
    out property <string> command_name <=> command.text;
    out property <string> topic_name <=> topic.text;
    in-out property <[{key: string, value: float}]> data:
    [{ key: "", value: 0.0 }];
    callback submit([{key: string, value: float}], string, string);
    callback add_item();
    title: "命令设置界面";
    ScrollView {
        height: parent.height;
        VerticalLayout {
            height: parent.height;
            width: parent.width;
            alignment: center;
            HorizontalBox {
                width: parent.width;
                Text {
                    width: 8rem;
                    text: "命令名称:";
                    font-family: "宋体";
                    font-size: 16px;
                    letter-spacing: 1px;
                    stroke-width: 1px;
                    stroke-style: center;
                    stroke: #6b2da4;
                    vertical-alignment: center;
                    horizontal-alignment: center;
                }

                Rectangle {
                    background: #8f9129af;
                    border-radius: 5px;
                    width: 120px;
                    command := TextInput {
                        text: "";
                        input-type: text;
                        font-family: "宋体";
                        font-size: 16px;
                        font-weight: 700;
                        color: #ffcdcd;
                        text-cursor-width: 10px;
                    }
                }

                Text {
                    width: 8rem;
                    text: "主题名称:";
                    font-family: "宋体";
                    font-size: 16px;
                    letter-spacing: 1px;
                    stroke-width: 1px;
                    stroke-style: center;
                    stroke: #6b2da4;
                    vertical-alignment: center;
                    horizontal-alignment: center;
                }

                Rectangle {
                    background: #2f2d88af;
                    border-radius: 5px;
                    width: 120px;
                    topic := TextInput {
                        text: "";
                        input-type: text;
                        font-family: "宋体";
                        font-size: 16px;
                        font-weight: 700;
                        color: #b3d0ff;
                        text-cursor-width: 10px;
                    }
                }
            }

            HorizontalBox {
                width: parent.width;
                ListView {
                    vertical-scrollbar-policy: always-on;
                    height: root.height - 160px;
                    width: parent.width - 10px;
                    for item[i] in data: Rectangle {
                        width: parent.width - 20px;
                        background: @radial-gradient(circle, #b834b1, #c7c8de 50%, #070715 100%);
                        border-radius: 8px;
                        border-color: #700867;
                        border-width: 3px;
                        drop-shadow-color: #08091c;
                        drop-shadow-blur: 15px;
                        drop-shadow-offset-y: 3px;
                        HorizontalBox {
                            width: parent.width - 50px;
                            HorizontalBox {
                                width: parent.width / 2;
                                Text {
                                    width: 5rem;
                                    text: "属性名:";
                                    font-family: "宋体";
                                    font-size: 16px;
                                    letter-spacing: 1px;
                                    stroke-width: 1px;
                                    stroke-style: center;
                                    stroke: #6b2da4;
                                    vertical-alignment: center;
                                    horizontal-alignment: center;
                                }

                                Rectangle {
                                    background: #ffffff2e;
                                    border-radius: 3px;
                                    TextInput {
                                        selection-background-color: #9c9c9c;
                                        text: item.key;
                                        input-type: text;
                                        vertical-alignment: center;
                                        text-cursor-width: 3px;
                                        edited => {
                                            data[i].key = self.text;
                                        }
                                    }
                                }
                            }

                            HorizontalBox {
                                width: parent.width / 2;
                                Text {
                                    text: "属性值:";
                                    font-family: "宋体";
                                    font-size: 16px;
                                    width: 5rem;
                                    letter-spacing: 1px;
                                    stroke-width: 1px;
                                    stroke-style: center;
                                    vertical-alignment: center;
                                    stroke: #6b2da4;
                                    horizontal-alignment: center;
                                }

                                Rectangle {
                                    background: #ffffff2e;
                                    border-radius: 3px;
                                    TextInput {
                                        selection-background-color: #9c9c9c;
                                        text: item.value;
                                        input-type: text;
                                        vertical-alignment: center;
                                        text-cursor-width: 3px;
                                        edited => {
                                            data[i].value = self.text.to-float();
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }

            HorizontalBox {
                alignment: center;
                GridBox {
                    width: 200px;
                    height: 60px;
                    spacing: 2px;
                    Rectangle {
                        border-radius: 10px;
                        border-width: 2px;
                        border-color: #ffde59;
                        width: parent.width;
                        height: parent.height;
                        drop-shadow-color: #060b9e;
                        drop-shadow-blur: 10px;
                        HorizontalBox {
                            alignment: center;
                            BeautifyButton {
                                text: "新增";
                                on_click => {
                                    add_item();
                                }
                            }

                            BeautifyButton {
                                text: "保存";
                                on_click => {
                                    submit(data, command_name,topic_name);
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
