import { BeautifyButton } from "beauty_button.slint";
import { Button, HorizontalBox } from "std-widgets.slint";
import { CommandInput } from "command_input.slint";
import { CommandSetWindow } from "command_set_window.slint";
export { 
    CommandSetWindow
 }
export component MainView inherits Window {
    callback on_click();
    callback open_command_set_window();
    width: 500px;
    height: 300px;
    HorizontalBox {
        CommandInput {
            name: "命令";
        }
        BeautifyButton {
            text: "Beautify";
            on_click => {
                open_command_set_window();
            }
        }
    }
}
